# Generated by Django 3.1.2 on 2020-10-25 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201024_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': False},
        ),
    ]
