# Generated by Django 3.1.1 on 2020-10-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201008_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsZipFipsV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(max_length=255)),
                ('countyname', models.CharField(db_column='CountyName', max_length=255)),
                ('state', models.CharField(db_column='State', max_length=255)),
                ('stcountyfips', models.CharField(db_column='STcountyFIPS', max_length=255)),
            ],
            options={
                'db_table': 'US_ZIP_FIPS_v2',
                'managed': False,
            },
        ),
    ]
